"""Generate src/lib/languages.ts from ../../language.md"""
from __future__ import annotations

import ast
from pathlib import Path


def label_from_key(k: str) -> str:
    parts: list[str] = []
    for word in k.split():
        if word.startswith("("):
            parts.append("(" + word[1:].capitalize())
        elif word.endswith(")"):
            parts.append(word[:-1].capitalize() + ")")
        else:
            parts.append(word.capitalize())
    return " ".join(parts)


def main() -> None:
    # frontend/scripts/ -> project root (AI translator)
    root = Path(__file__).resolve().parents[2]
    md_path = root / "language.md"
    text = md_path.read_text(encoding="utf-8").strip()
    data: dict[str, str] = ast.literal_eval(text)

    items = [(code, label_from_key(name)) for name, code in data.items()]
    uniq: list[tuple[str, str]] = []
    seen: set[str] = set()
    for code, lab in sorted(items, key=lambda x: (x[1].lower(), x[0])):
        if code in seen:
            continue
        seen.add(code)
        uniq.append((code, lab))

    extras = [("pt-BR", "Portuguese (Brazil)")]
    for code, lab in reversed(extras):
        if code not in seen:
            uniq.insert(0, (code, lab))
            seen.add(code)

    out = root / "frontend" / "src" / "lib" / "languages.ts"
    lines = [
        "/** Generated by scripts/gen_languages_ts.py from ../../language.md */",
        "",
        "export type TargetLanguageOption = { readonly code: string; readonly label: string };",
        "",
        "/** BCP-47 / locale codes passed as target_language to the API */",
        "export const TARGET_LANGUAGES: readonly TargetLanguageOption[] = [",
    ]
    for code, lab in uniq:
        escaped = lab.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  {{ code: "{code}", label: "{escaped}" }},')
    lines.extend(
        [
            "];",
            "",
            "/** Matches prior UI default */",
            'export const DEFAULT_TARGET_LANGUAGE_CODE = "pt-BR";',
            "",
            "export function findLanguageLabel(code: string): string | undefined {",
            "  return TARGET_LANGUAGES.find((o) => o.code === code)?.label;",
            "}",
            "",
        ]
    )
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(uniq)} languages -> {out}")


if __name__ == "__main__":
    main()
